-- CREATE A DATABASE AND CREATE A TABLE INSIDE IT
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;

USE hbtn_0d_usa;

CREATE TABLE IF NOT EXISTS cities(
    id INT NOT NULL AUTO_INCREMENT UNIQUE PRIMARY KEY,
     state_id INT NOT NULL,
    name VARCHAR(256) NOT NULL,
    FOREIGN KEY (state_id) REFERENCES states(id)
);
-- The requierements had been respected